packages:
  - "packages/@ghostd/react"
  - "packages/@ghostd-web/core"
  - "packages/@ghostd-web/client"
  - "packages/@ghostd-web/dom"
  - "packages/@internal/ts"

minimumReleaseAge: 2880

allowBuilds:
  "esbuild": false
