// Generated by scripts/generate-embedded-assets.mjs. Do not edit.
pub const Asset = struct {
    path: []const u8,
    content_type: []const u8,
    body: []const u8,
};

pub const assets = [_]Asset{
    .{ .path = "/assets/index-BzOJROtX.js", .content_type = "text/javascript; charset=utf-8", .body = @embedFile("embedded_asset_files/assets/index-BzOJROtX.js") }, // 243661 bytes,
    .{ .path = "/assets/index-CtAOGc52.css", .content_type = "text/css; charset=utf-8", .body = @embedFile("embedded_asset_files/assets/index-CtAOGc52.css") }, // 4536 bytes,
    .{ .path = "/index.html", .content_type = "text/html; charset=utf-8", .body = @embedFile("embedded_asset_files/index.html") }, // 690 bytes,
    .{ .path = "/", .content_type = "text/html; charset=utf-8", .body = @embedFile("embedded_asset_files/index.html") }, // 690 bytes
};
