// Generated by scripts/generate-embedded-assets.mjs. Do not edit.
pub const Asset = struct {
    path: []const u8,
    content_type: []const u8,
    body: []const u8,
};

pub const assets = [_]Asset{
    .{ .path = "/assets/index-CguZafAj.js", .content_type = "text/javascript; charset=utf-8", .body = @embedFile("embedded_asset_files/assets/index-CguZafAj.js") }, // 49874 bytes,
    .{ .path = "/assets/index-CpuV251Q.css", .content_type = "text/css; charset=utf-8", .body = @embedFile("embedded_asset_files/assets/index-CpuV251Q.css") }, // 3064 bytes,
    .{ .path = "/index.html", .content_type = "text/html; charset=utf-8", .body = @embedFile("embedded_asset_files/index.html") }, // 2215 bytes,
    .{ .path = "/", .content_type = "text/html; charset=utf-8", .body = @embedFile("embedded_asset_files/index.html") }, // 2215 bytes
};
